### ISSUE TITLE
Reflection on implementing the first page (landing.html)

### ISSUE THREAD

**Issue by s8sun** [cse110-fa21-group17/cse110-fa21-group17#13]
# Reflection on our first html task
Since this is our first html task, after completing it you should have some idea on what the process is. This is a reflection task. This task should be assigned to the same person who did #11 
### Answer these questions and discuss during team meetings:
1. How long did the task took you?
2. What problems did you face?
3. Were the task definitions clear enough?
4. Would it help to do paired programming, or you prefer working alone? 
5. How was your experience working with you team lead / manager?

### Define syntax standards:
We should also define syntax standards, here are some things we can talk about.
1. What editor did you use, what is the `html` template you used?
2. Indentation: `tab` or `spaces`? We need to pick on and stick with it.
3. General html good practice? Let's go through the list and discuss https://www.webtips.dev/10-best-practices-for-html

**Comment by cbj99** [comment]
**Answer these questions and discuss during team meetings:**
**_How long did the task took you?_**： It took me about a day.
**_What problems did you face?_**： CSS really tortured me. Also, the carousel functionality took us some time to understand and revise.
**_Were the task definitions clear enough?_**: Yes
**_Would it help to do paired programming, or do you prefer working alone?_**: I really like paired programming. But to be honest, Live Server might not be the best choice since my code might do something unexpected to others' code if we are editing at the same time.
**_How was your experience working with your team lead / manager?_**: I love them. They are great.

**Comment by jkwok626** [comment]
**How long did the task take you?**
About a day

**What problems did you face?**
The Bootstrap carousel was definitely the biggest problem. Some of the examples that we found online had many lines of code that we didn't understand so they were hard to modify. We ended up going with an example from Bootstrap's site and we built off of it. 
The page is not responsive right now so it looks super zoomed in on smaller screens. 

**Were the task definitions clear enough?**
Yes

**Would it help to do paired programming, or you prefer working alone?**
I really liked paired programming. 

**How was your experience working with your team lead / manager?**
It's been good.
